env:
  - GO111MODULE=on
  - GOPROXY=https://gocenter.io

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - 386
      - amd64
      - arm
      - arm64
  - env:
      - CGO_ENABLED=0
    flags:
      - -a
    ldflags:
      - -extldflags "-static"
    goos:
      - linux
    goarch:
      - 386
      - amd64
      - arm
      - arm64

brews:
  - tap:
      owner: fubarhouse
      name: homebrew-pygmy-go
    folder: Formula
    homepage: "https://github.com/fubarhouse/pygmy-go"
    description: "amazee.io's local development helper tool"
    skip_upload: false
    test: system "#{bin}/pygmy-go version"
    install: bin.install "pygmy-go"
