env:
  - GO111MODULE=on
  - GOPROXY=https://gocenter.io

archives:
  - id: pygmy-go
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    builds:
      - pygmy-go
  - id: pygmy-go-static
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}_static"
    builds:
      - pygmy-go-static
builds:
  - id: pygmy-go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - 386
      - amd64
      - arm
      - arm64
  - id: pygmy-go-static
    env:
      - CGO_ENABLED=0
    flags:
      - -a
    ldflags:
      - -extldflags "-static"
    goos:
      - linux
    goarch:
      - 386
      - amd64
      - arm
      - arm64

brews:
  - ids:
    - pygmy-go
    tap:
      owner: pygmystack
      name: homebrew-pygmy
    folder: Formula
    homepage: "https://github.com/pygmystack/pygmy"
    description: "amazee.io's local development helper tool"
    skip_upload: false
    test: system "#{bin}/pygmy-go version"
    install: bin.install "pygmy-go"
