version: 2
env:
  - GO111MODULE=on
  - GOPROXY=https://gocenter.io

archives:
  - id: pygmy
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    builds:
      - pygmy
  - id: pygmy-static
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}_static"
    builds:
      - pygmy-static

builds:
  - id: pygmy
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s
      - -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
      - -X main.GoOS={{.Os}}
      - -X main.GoArch={{.Arch}}
    goos:
      - linux
      - darwin
    goarch:
      - 386
      - amd64
      - arm
      - arm64
  - id: pygmy-windows
    env:
      - CGO_ENABLED=0
    goos:
      - windows
    goarch:
      - 386
      - amd64
      - arm
    flags:
      - -a
    ldflags:
      - -s
      - -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
      - -X main.GoOS={{.Os}}
      - -X main.GoArch={{.Arch}}
  - id: pygmy-static
    env:
      - CGO_ENABLED=0
    flags:
      - -a
    ldflags:
      - -s
      - -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
      - -X main.GoOS={{.Os}}
      - -X main.GoArch={{.Arch}}
      - -extldflags "-static"
    goos:
      - linux
    goarch:
      - 386
      - amd64
      - arm
      - arm64

snapshot:
  version_template: "{{ .Version }}-SNAPSHOT-{{.ShortCommit}}"

brews:
  - ids:
    - pygmy
    repository:
      owner: pygmystack
      name: homebrew-pygmy
      branch: main
      token: "${{ .Env.GITHUB_TOKEN }}"
    homepage: "https://github.com/pygmystack/pygmy"
    description: "amazee.io's local development helper tool"
    skip_upload: false
    test: system "#{bin}/pygmy version"
    install: bin.install "pygmy"