package resolv

type Resolv struct {
	File     string
	Contents string
	Path     string
}

type resolv interface {
	Clean()
	Configure()
	New() Resolv
	Status() bool
}

var ResolvOSX = Resolv{
	Contents: "\n# Generated by amazeeio pygmy\nnameserver 127.0.0.1\nport 6053\n",
	File:     "docker.amazee.io",
	Path:     "/etc/resolver",
}

var ResolvGeneric = Resolv{
	File:     "resolv.conf",
	Contents: "\nnameserver 127.0.0.1 # added by amazee.io pygmy",
	Path:     "/etc",
}
